### ISSUE TITLE
Error when running `npm run test-browser`

### ISSUE THREAD

**Issue by blackwatertepes** [ethereum/browser-solidity#892]
```
$ npm run test-browser

> browser-solidity@0.0.0 test-browser /Users/tylerkuhn/Sites/browser-solidity
> npm-run-all -lpr selenium downloadsolc make-mock-compiler serve browsertest

[selenium          ] 
[selenium          ] > browser-solidity@0.0.0 selenium /Users/tylerkuhn/Sites/browser-solidity
[selenium          ] > execr --silent selenium-standalone start
[selenium          ] 
[downloadsolc      ] 
[downloadsolc      ] > browser-solidity@0.0.0 downloadsolc /Users/tylerkuhn/Sites/browser-solidity
[downloadsolc      ] > rimraf soljson.js; wget https://ethereum.github.io/solc-bin/soljson.js
[downloadsolc      ] 
[make-mock-compiler] 
[make-mock-compiler] > browser-solidity@0.0.0 make-mock-compiler /Users/tylerkuhn/Sites/browser-solidity
[make-mock-compiler] > node ci/makeMockCompiler.js
[make-mock-compiler] 
[serve             ] 
[serve             ] > browser-solidity@0.0.0 serve /Users/tylerkuhn/Sites/browser-solidity
[serve             ] > execr --silent http-server .
[serve             ] 
[browsertest       ] 
[browsertest       ] > browser-solidity@0.0.0 browsertest /Users/tylerkuhn/Sites/browser-solidity
[browsertest       ] > sleep 5 && npm run nightwatch_local
[browsertest       ] 
[downloadsolc      ] --2017-10-31 15:03:50--  https://ethereum.github.io/solc-bin/soljson.js
[downloadsolc      ] Resolving ethereum.github.io... 
[make-mock-compiler] module.js:472
[make-mock-compiler]     throw err;
[make-mock-compiler]     ^
[make-mock-compiler] 
[make-mock-compiler] Error: Cannot find module '../soljson'
[make-mock-compiler]     at Function.Module._resolveFilename (module.js:470:15)
[make-mock-compiler]     at Function.Module._load (module.js:418:25)
[make-mock-compiler]     at Module.require (module.js:498:17)
[make-mock-compiler]     at require (internal/module.js:20:19)
[make-mock-compiler]     at Object.<anonymous> (/Users/tylerkuhn/Sites/browser-solidity/ci/makeMockCompiler.js:5:15)
[make-mock-compiler]     at Module._compile (module.js:571:32)
[make-mock-compiler]     at Object.Module._extensions..js (module.js:580:10)
[make-mock-compiler]     at Module.load (module.js:488:32)
[make-mock-compiler]     at tryModuleLoad (module.js:447:12)
[make-mock-compiler]     at Function.Module._load (module.js:439:3)
[make-mock-compiler] 
[make-mock-compiler] npm ERR! Darwin 15.6.0
[make-mock-compiler] npm ERR! argv "/Users/tylerkuhn/.nvm/versions/node/v7.10.1/bin/node" "/Users/tylerkuhn/.nvm/versions/node/v7.10.1/lib/node_modules/npm/bin/npm-cli.js" "run" "make-mock-compiler"
[make-mock-compiler] npm ERR! node v7.10.1
[make-mock-compiler] npm ERR! npm  v4.2.0
[make-mock-compiler] npm ERR! code ELIFECYCLE
[make-mock-compiler] npm ERR! errno 1
[make-mock-compiler] npm ERR! browser-solidity@0.0.0 make-mock-compiler: `node ci/makeMockCompiler.js`
[make-mock-compiler] npm ERR! Exit status 1
[make-mock-compiler] npm ERR! 
[make-mock-compiler] npm ERR! Failed at the browser-solidity@0.0.0 make-mock-compiler script 'node ci/makeMockCompiler.js'.
[make-mock-compiler] npm ERR! Make sure you have the latest version of node.js and npm installed.
[make-mock-compiler] npm ERR! If you do, this is most likely a problem with the browser-solidity package,
[make-mock-compiler] npm ERR! not with npm itself.
[make-mock-compiler] npm ERR! Tell the author that this fails on your system:
[make-mock-compiler] npm ERR!     node ci/makeMockCompiler.js
[make-mock-compiler] npm ERR! You can get information on how to open an issue for this project with:
[make-mock-compiler] npm ERR!     npm bugs browser-solidity
[make-mock-compiler] npm ERR! Or if that isn't available, you can get their info via:
[make-mock-compiler] npm ERR!     npm owner ls browser-solidity
[make-mock-compiler] npm ERR! There is likely additional logging output above.
[make-mock-compiler] 
[make-mock-compiler] npm ERR! Please include the following file with any support request:
[make-mock-compiler] npm ERR!     /Users/tylerkuhn/.npm/_logs/2017-10-31T22_03_50_498Z-debug.log
ERROR: "make-mock-compiler" exited with 1.
```

I've double checked my versions with the Travis build, and downloading soljson with `npm run dowloadsolc` seems to work. Any other suggestions?

**Comment by yann300** [comment]
Seems solc failed to download. Please download it again.
if you just want to run a local copy of Remix, just run
`npm install && npm run build && npm run serve`
