### ISSUE TITLE
How to return array of structs ? 

### ISSUE THREAD

**Issue by mimitc123** [ethereum/browser-solidity#920]
contract Donate{

struct DonateInfo{
    uint id;
    uint value;
    uint time;
}

DonateInfo[] public list;

function all() public returns (DonateInfo []){
    return list;
}
}

When execute the return array function it says below
Failed to decode output: Error: Unsupported or invalid type: tuple

**Comment by 3esmit** [comment]
Not supported yet. use 
```javascript
function all(uint pos) public constant returns(uint id, uint value, uint time)`{ 
DonateInfo storage di = list[pos];
return (di.id, di.value, di.time)
} 
```

**Comment by yann300** [comment]
closing

**Comment by jebadar** [comment]
I am still getting this error need help on solidity version : 0.4.23
Error: invalid solidity type!: tuple[]
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at XMLHttpRequest._setReadyState (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest.request.onreadystatechange (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
    at C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:89:1
    at C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\method.js:142:1
    at Object.callback (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\function.js:145:1)
    at SolidityFunction.unpackOutput (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\function.js:113:1)
    at SolidityCoder.decodeParams (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\solidity\coder.js:203:1)
    at SolidityCoder.getSolidityTypes (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\solidity\coder.js:230:1)
    at Array.map (<anonymous>)
    at C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\solidity\coder.js:231:1
    at SolidityCoder._requireType (C:\Users\KikBits\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\solidity\coder.js:61:1)
