### ISSUE TITLE
error npm install(Error: Cannot find module './helpers/traceHelper')

### ISSUE THREAD

**Issue by shiro83** [ethereum/browser-solidity#922]
What should I do if I get this error?

OSX 10.12.6

```
$ npm install

> browser-solidity@0.0.0 build /Users/zawa/dev/browser-solidity
> browserify src/index.js -o build/app.js

Error: Cannot find module './helpers/traceHelper' from '/Users/zawa/dev/browser-solidity/node_modules/remix-solidity/node_modules/remix-lib'
    at /Users/zawa/dev/browser-solidity/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/zawa/dev/browser-solidity/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/zawa/dev/browser-solidity/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/zawa/dev/browser-solidity/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! browser-solidity@0.0.0 build: `browserify src/index.js -o build/app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the browser-solidity@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zawa/.npm/_logs/2017-12-03T01_38_53_233Z-debug.log
```

**Comment by yann300** [comment]
doesn't seem to go over the `install` process but just start building... how do you pull browser-solidity? can you update it, remove `nodes_module` and reinstall?

**Comment by shiro83** [comment]
Thank you! 
Succeeded!

```
$ rm -rf browser-solidity
$ git clone https://github.com/ethereum/browser-solidity
$ cd browser-solidity
$ npm install
```

**Comment by chainhead** [comment]
For me, I could get it working by first installing `make` and then `browser-solidity`.

```
rm -rf node_modules
npm install make
npm install
```
